/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package n2ds1.caio.lobo.GUI;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import n2ds1.caio.lobo.Control.TipoControl;
import n2ds1.caio.lobo.model.Imovel;
import n2ds1.caio.lobo.model.Tipo;

/**
 *
 * @author hellk
 */
public class TipoGUI extends javax.swing.JFrame {

    /**
     * Creates new form TipoGUI
     */
    public TipoGUI() throws SQLException {
        initComponents();
        StartSet();
        txtID.setEditable(false);
        DefaultListModel model = new DefaultListModel();
        listImoveis.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listImoveis = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTipos = new javax.swing.JTable();
        btmSalvar = new javax.swing.JButton();
        btmCancelar = new javax.swing.JButton();
        btmNovo = new javax.swing.JButton();
        btmEditar = new javax.swing.JButton();
        btmRemover = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Descricao");

        jLabel3.setText("Imoveis");

        jLabel4.setText("Tipos");

        jScrollPane1.setViewportView(listImoveis);

        tblTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTipos.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tblTipos);
        tblTipos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btmSalvar.setText("Salvar");
        btmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalvarActionPerformed(evt);
            }
        });

        btmCancelar.setText("Cancelar");
        btmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelarActionPerformed(evt);
            }
        });

        btmNovo.setText("Novo");
        btmNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNovoActionPerformed(evt);
            }
        });

        btmEditar.setText("Editar");
        btmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEditarActionPerformed(evt);
            }
        });

        btmRemover.setText("Remover");
        btmRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRemoverActionPerformed(evt);
            }
        });

        txtNome.setText("jTextField1");

        txtDescricao.setText("jTextField2");

        jLabel5.setText("ID");

        txtID.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btmSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmRemover))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmSalvar)
                    .addComponent(btmCancelar)
                    .addComponent(btmNovo)
                    .addComponent(btmEditar)
                    .addComponent(btmRemover))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRemoverActionPerformed
        // TODO add your handling code here:
        TipoControl controle = new TipoControl();
                
       
        try {
           
            controle.excluir(controle.getTipoPorId(Long.parseLong(txtID.getText())));
        } catch (SQLException ex) {
            Logger.getLogger(TipoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btmRemoverActionPerformed

    private void btmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalvarActionPerformed
        // TODO add your handling code here:
        TipoControl control = new TipoControl();
        
       
            Tipo i = new Tipo();
            if(!"Gerado Automaticamente".equals(txtID.getText())) {
                i.setId(Long.parseLong(txtID.getText()));
        } else {
                i.setId(null);
        }
            i.setDescricao(txtDescricao.getText());
            i.setNome(txtNome.getText());
         
        try {
            control.gravar(i);
        } catch (SQLException ex) {
            Logger.getLogger(TipoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            atualizarListaTipos();
        } catch (SQLException ex) {
            Logger.getLogger(TipoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        textClear();
        
        
        
        
        
        
    }//GEN-LAST:event_btmSalvarActionPerformed

    private void btmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelarActionPerformed
        // TODO add your handling code here:
        textClear();
        textBlock();
        buttonStartSet();
        try {
            atualizarListaTipos();
        } catch (SQLException ex) {
            Logger.getLogger(TipoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btmCancelarActionPerformed

    private void btmNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNovoActionPerformed
        // TODO add your handling code here:
        textClear();
        textUnblock();
        buttonNewSet();
        
        
    }//GEN-LAST:event_btmNovoActionPerformed

    private void btmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEditarActionPerformed
        // TODO add your handling code here:
        if(tblTipos.getSelectedRowCount()>0){
        TipoControl controle = new TipoControl();
                
        Object o = ((DefaultTableModel) tblTipos.getModel()).getValueAt(tblTipos.getSelectedRow(),0);
        try{
            textClear();
            
            Tipo i =  controle.getTipoPorId((Long) o);
            i.setImoveis(controle.listarImoveis(i.getId()));
            
            
            txtDescricao.setText(i.getDescricao());
            txtID.setText(i.getId().toString());
            txtNome.setText(i.getNome());
            setListImoveis(i);
            
          
        } catch (SQLException ex) {
            Logger.getLogger(ImovelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        textUnblock();
        buttonEditSet();
        }
        else JOptionPane.showConfirmDialog(this, "Favor selecionar um Tipo na lista");
    }//GEN-LAST:event_btmEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TipoGUI().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TipoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmEditar;
    private javax.swing.JButton btmNovo;
    private javax.swing.JButton btmRemover;
    private javax.swing.JButton btmSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Imovel> listImoveis;
    private javax.swing.JTable tblTipos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void StartSet() throws SQLException {
        textClear();
     atualizarListaTipos();
     buttonStartSet();
     textBlock();
     
    }

    private void textClear() {
    
        txtID.setText("Gerado Automaticamente");
        txtDescricao.setText("");
        txtDescricao.setEnabled(false);
        txtNome.setText("");
        txtNome.setEnabled(false);
        
        listImoveis.removeAll();
    }

    

    private void buttonStartSet() {
        btmCancelar.setEnabled(false);
        btmEditar.setEnabled(true);
        btmNovo.setEnabled(true);
        btmRemover.setEnabled(false);
        btmSalvar.setEnabled(false);
          
    }

    private void atualizarListaTipos() throws SQLException {
        
        TipoControl control = new TipoControl();
        control.atualizarLista(tblTipos);
     
    }

    private void textBlock() {
        txtDescricao.setEnabled(false);
        txtNome.setEnabled(false);
    }

    private void textUnblock() {
        txtDescricao.setEnabled(true);
        txtNome.setEnabled(true);
    }

    private void buttonNewSet() {
        btmCancelar.setEnabled(true);
        btmEditar.setEnabled(false);
        btmNovo.setEnabled(false);
        btmRemover.setEnabled(false);
        btmSalvar.setEnabled(true); }

    private void buttonEditSet() {
      buttonNewSet();
      btmRemover.setEnabled(true);
    }

    private void setListImoveis(Tipo t) {
     DefaultListModel model = (DefaultListModel) listImoveis.getModel();
     TipoControl control = new TipoControl();
                model.clear();
                for(Imovel ri: t.getImoveis()){
                    model.addElement(ri);
                }
    }
}